2023-03-11 08:45:29,615 INFO    MainThread:27037 [wandb_setup.py:_flush():71] setting env: {'silent': 'true'}
2023-03-11 08:45:29,617 INFO    MainThread:27037 [wandb_setup.py:_flush():71] setting login settings: {}
2023-03-11 08:45:29,620 INFO    MainThread:27037 [wandb_setup.py:_flush():71] [34m[1mwandb[0m: Network error (ConnectionError), entering retry loop.
2023-03-11 08:45:29,623 INFO    MainThread:27037 [wandb_setup.py:_flush():71] [34m[1mwandb[0m: wandb version 0.13.11 is available!  To upgrade, please run:
[34m[1mwandb[0m:  $ pip install wandb --upgrade
2023-03-11 08:45:29,625 INFO    MainThread:27037 [wandb_setup.py:_flush():71] [34m[1mwandb[0m: You can find your API key in your browser here: http://wandb.your-shared-local-host.com/authorize
2023-03-11 08:45:29,628 ERROR   MainThread:27037 [wandb_setup.py:_flush():71] [34m[1mwandb[0m: [32m[41mERROR[0m API key must be 40 characters long, yours was 60
2023-03-11 08:45:29,631 INFO    MainThread:27037 [wandb_setup.py:_flush():71] [34m[1mwandb[0m: You can find your API key in your browser here: http://wandb.your-shared-local-host.com/authorize
2023-03-11 08:45:29,633 INFO    MainThread:27037 [wandb_setup.py:_flush():71] [34m[1mwandb[0m: Appending key for wandb.your-shared-local-host.com to your netrc file: /root/.netrc
2023-03-11 08:45:29,637 INFO    MainThread:27037 [wandb_setup.py:_flush():71] [34m[1mwandb[0m: wandb version 0.13.11 is available!  To upgrade, please run:
[34m[1mwandb[0m:  $ pip install wandb --upgrade
2023-03-11 08:45:29,643 INFO    MainThread:27037 [wandb_setup.py:_flush():71] [34m[1mwandb[0m: wandb version 0.13.11 is available!  To upgrade, please run:
[34m[1mwandb[0m:  $ pip install wandb --upgrade
2023-03-11 08:45:29,648 INFO    MainThread:27037 [wandb_setup.py:_flush():71] [34m[1mwandb[0m: wandb version 0.13.11 is available!  To upgrade, please run:
[34m[1mwandb[0m:  $ pip install wandb --upgrade
2023-03-11 08:45:29,654 INFO    MainThread:27037 [wandb_setup.py:_flush():71] [34m[1mwandb[0m: wandb version 0.13.11 is available!  To upgrade, please run:
[34m[1mwandb[0m:  $ pip install wandb --upgrade
2023-03-11 08:45:29,660 INFO    MainThread:27037 [wandb_init.py:_log_setup():371] Logging user logs to /workspace/wandb/run-20230311_084529-h4uga9uf/logs/debug.log
2023-03-11 08:45:29,665 INFO    MainThread:27037 [wandb_init.py:_log_setup():372] Logging internal logs to /workspace/wandb/run-20230311_084529-h4uga9uf/logs/debug-internal.log
2023-03-11 08:45:29,668 INFO    MainThread:27037 [wandb_init.py:init():404] calling init triggers
2023-03-11 08:45:29,671 INFO    MainThread:27037 [wandb_init.py:init():411] wandb.init called with sweep_config: {}
config: {'CONTACT_IMG_DIR': '/workspace/input/contact_images', 'DEBUG': True, 'EXP_CATEGORY': 'DEBUG', 'EXP_NAME': 'DEBUG', 'INPUT_DIR': '/workspace/input', 'MODEL_DIR': '/workspace/output/DEBUG/model', 'OUTPUT_DIR': '/workspace/output', 'SAVED_CONTACT_CSV': '/workspace/input/Saved_contact_frames.csv', 'TRAIN_HELMET_CSV': '/workspace/input/train_baseline_helmets.csv', 'TRAIN_LABEL_CSV': '/workspace/input/train_labels.csv', 'TRAIN_TRACKING_CSV': '/workspace/input/train_player_tracking.csv', 'TRAIN_VIDEO_META_CSV': '/workspace/input/train_video_metadata.csv', 'TRAIN_VIDEO_NUM': 100, 'T_max': 10, 'VALID_VIDEO_NUM': 10, 'batch_size': 32, 'features': ['x_position_1', 'y_position_1', 'x_position_2', 'y_position_2', 'speed_1', 'distance_1', 'direction_1', 'orientation_1', 'acceleration_1', 'sa_1', 'speed_2', 'distance_2', 'direction_2', 'orientation_2', 'acceleration_2', 'sa_2', 'players_dis'], 'img_size': [224, 224], 'inp_channels': 3, 'kaggle': False, 'lr': 0.0001, 'masksize_helmet_ratio': 4, 'min_lr': 1e-08, 'model_name': 'swin_s3_tiny_224', 'n_epoch': 2, 'n_folds': 3, 'num_img_feature': 10, 'num_workers': 2, 'out_features': 20, 'pretrained': True, 'print_freq': 1000, 'random_seed': 21, 'roll_sum_window_size': 10, 'sample_num': 1000, 'train_folds': [0, 1, 2], 'wandb': True, 'weight_decay': 1e-06}
2023-03-11 08:45:29,672 INFO    MainThread:27037 [wandb_init.py:init():460] starting backend
2023-03-11 08:45:29,675 INFO    MainThread:27037 [backend.py:_multiprocessing_setup():101] multiprocessing start_methods=fork,spawn,forkserver, using: spawn
2023-03-11 08:45:29,686 INFO    MainThread:27037 [backend.py:ensure_launched():216] starting backend process...
2023-03-11 08:45:29,696 INFO    MainThread:27037 [backend.py:ensure_launched():222] started backend process with pid: 3969
2023-03-11 08:45:29,698 INFO    MainThread:27037 [wandb_init.py:init():469] backend started and connected
2023-03-11 08:45:29,711 INFO    MainThread:27037 [wandb_run.py:_label_probe_notebook():911] probe notebook
2023-03-11 08:45:29,713 ERROR   MainThread:27037 [jupyter.py:attempt_kaggle_load_ipynb():279] Unable to load kaggle notebook
Traceback (most recent call last):
  File "/opt/conda/lib/python3.7/site-packages/wandb/jupyter.py", line 273, in attempt_kaggle_load_ipynb
    client = kaggle.UserSessionClient()
  File "/root/.local/lib/python3.7/site-packages/kaggle_session.py", line 14, in __init__
    self.web_client = KaggleWebClient()
  File "/root/.local/lib/python3.7/site-packages/kaggle_web_client.py", line 30, in __init__
    'A JWT Token is required to call Kaggle, '
kaggle_web_client.CredentialError: A JWT Token is required to call Kaggle, but none found in environment variable KAGGLE_USER_SECRETS_TOKEN
2023-03-11 08:45:29,715 INFO    MainThread:27037 [wandb_run.py:_label_probe_notebook():921] Unable to probe notebook: 'NoneType' object has no attribute 'get'
2023-03-11 08:45:29,716 INFO    MainThread:27037 [wandb_init.py:init():533] updated telemetry
2023-03-11 08:45:29,778 INFO    MainThread:27037 [wandb_init.py:init():563] communicating current version
2023-03-11 08:45:30,529 INFO    MainThread:27037 [wandb_init.py:init():568] got version response upgrade_message: "wandb version 0.13.11 is available!  To upgrade, please run:\n $ pip install wandb --upgrade"

2023-03-11 08:45:30,533 INFO    MainThread:27037 [wandb_init.py:init():578] communicating run to backend with 30 second timeout
2023-03-11 08:45:51,322 WARNING MainThread:27037 [wandb_init.py:init():952] interrupted
Traceback (most recent call last):
  File "/opt/conda/lib/python3.7/site-packages/wandb/sdk/wandb_init.py", line 931, in init
    run = wi.init()
  File "/opt/conda/lib/python3.7/site-packages/wandb/sdk/wandb_init.py", line 579, in init
    ret = backend.interface.communicate_run(run, timeout=30)
  File "/opt/conda/lib/python3.7/site-packages/wandb/sdk/interface/interface.py", line 210, in communicate_run
    return self._communicate_run(run, timeout=timeout)
  File "/opt/conda/lib/python3.7/site-packages/wandb/sdk/interface/interface_shared.py", line 311, in _communicate_run
    resp = self._communicate(req, timeout=timeout)
  File "/opt/conda/lib/python3.7/site-packages/wandb/sdk/interface/interface_shared.py", line 213, in _communicate
    return self._communicate_async(rec, local=local).get(timeout=timeout)
  File "/opt/conda/lib/python3.7/site-packages/wandb/sdk/interface/router.py", line 37, in get
    is_set = self._object_ready.wait(timeout)
  File "/opt/conda/lib/python3.7/threading.py", line 552, in wait
    signaled = self._cond.wait(timeout)
  File "/opt/conda/lib/python3.7/threading.py", line 300, in wait
    gotit = waiter.acquire(True, timeout)
KeyboardInterrupt
