2023-03-11 08:42:58,554 INFO    MainThread:31975 [wandb_setup.py:_flush():71] setting env: {}
2023-03-11 08:42:58,555 INFO    MainThread:31975 [wandb_setup.py:_flush():71] setting login settings: {}
2023-03-11 08:42:58,557 INFO    MainThread:31975 [wandb_init.py:_log_setup():371] Logging user logs to /workspace/nfl_utils/wandb/run-20230311_084258-24z95sh0/logs/debug.log
2023-03-11 08:42:58,558 INFO    MainThread:31975 [wandb_init.py:_log_setup():372] Logging internal logs to /workspace/nfl_utils/wandb/run-20230311_084258-24z95sh0/logs/debug-internal.log
2023-03-11 08:42:58,559 INFO    MainThread:31975 [wandb_init.py:init():404] calling init triggers
2023-03-11 08:42:58,560 INFO    MainThread:31975 [wandb_init.py:init():411] wandb.init called with sweep_config: {}
config: {}
2023-03-11 08:42:58,561 INFO    MainThread:31975 [wandb_init.py:init():460] starting backend
2023-03-11 08:42:58,562 INFO    MainThread:31975 [backend.py:_multiprocessing_setup():101] multiprocessing start_methods=fork,spawn,forkserver, using: spawn
2023-03-11 08:42:58,574 INFO    MainThread:31975 [backend.py:ensure_launched():216] starting backend process...
2023-03-11 08:42:58,580 INFO    MainThread:31975 [backend.py:ensure_launched():222] started backend process with pid: 1713
2023-03-11 08:42:58,582 INFO    MainThread:31975 [wandb_init.py:init():469] backend started and connected
2023-03-11 08:42:58,585 INFO    MainThread:31975 [wandb_init.py:init():533] updated telemetry
2023-03-11 08:42:58,618 INFO    MainThread:31975 [wandb_init.py:init():563] communicating current version
2023-03-11 08:42:59,403 INFO    MainThread:31975 [wandb_init.py:init():568] got version response upgrade_message: "wandb version 0.13.11 is available!  To upgrade, please run:\n $ pip install wandb --upgrade"

2023-03-11 08:42:59,405 INFO    MainThread:31975 [wandb_init.py:init():578] communicating run to backend with 30 second timeout
2023-03-11 08:43:29,407 INFO    MainThread:31975 [interface_shared.py:_communicate_run():313] couldn't get run from backend
2023-03-11 08:43:29,410 ERROR   MainThread:31975 [wandb_init.py:init():583] backend process timed out
2023-03-11 08:43:29,412 ERROR   MainThread:31975 [wandb_init.py:init():592] encountered error: Error communicating with wandb process
try: wandb.init(settings=wandb.Settings(start_method='fork'))
or:  wandb.init(settings=wandb.Settings(start_method='thread'))
For more info see: https://docs.wandb.ai/library/init#init-start-error
2023-03-11 08:43:29,417 ERROR   MainThread:31975 [wandb_init.py:init():958] error
Traceback (most recent call last):
  File "/opt/conda/lib/python3.7/site-packages/wandb/sdk/wandb_init.py", line 931, in init
    run = wi.init()
  File "/opt/conda/lib/python3.7/site-packages/wandb/sdk/wandb_init.py", line 596, in init
    backend.cleanup()
  File "/opt/conda/lib/python3.7/site-packages/wandb/sdk/backend/backend.py", line 245, in cleanup
    self.interface.join()
  File "/opt/conda/lib/python3.7/site-packages/wandb/sdk/interface/interface_shared.py", line 458, in join
    super().join()
  File "/opt/conda/lib/python3.7/site-packages/wandb/sdk/interface/interface.py", line 599, in join
    _ = self._communicate_shutdown()
  File "/opt/conda/lib/python3.7/site-packages/wandb/sdk/interface/interface_shared.py", line 455, in _communicate_shutdown
    _ = self._communicate(record)
  File "/opt/conda/lib/python3.7/site-packages/wandb/sdk/interface/interface_shared.py", line 213, in _communicate
    return self._communicate_async(rec, local=local).get(timeout=timeout)
  File "/opt/conda/lib/python3.7/site-packages/wandb/sdk/interface/interface_shared.py", line 218, in _communicate_async
    raise Exception("The wandb backend process has shutdown")
Exception: The wandb backend process has shutdown
2023-03-11 08:44:08,270 INFO    MainThread:31975 [wandb_settings.py:_apply_source_login():805] setting login settings: {}
2023-03-11 08:44:08,354 INFO    MainThread:31975 [wandb_setup.py:_flush():71] setting env: {}
2023-03-11 08:44:08,356 INFO    MainThread:31975 [wandb_setup.py:_flush():71] setting login settings: {}
2023-03-11 08:44:08,360 INFO    MainThread:31975 [wandb_init.py:_log_setup():371] Logging user logs to /workspace/nfl_utils/wandb/run-20230311_084408-1lxv4851/logs/debug.log
2023-03-11 08:44:08,364 INFO    MainThread:31975 [wandb_init.py:_log_setup():372] Logging internal logs to /workspace/nfl_utils/wandb/run-20230311_084408-1lxv4851/logs/debug-internal.log
2023-03-11 08:44:08,368 INFO    MainThread:31975 [wandb_init.py:init():404] calling init triggers
2023-03-11 08:44:08,372 INFO    MainThread:31975 [wandb_init.py:init():411] wandb.init called with sweep_config: {}
config: {}
2023-03-11 08:44:08,376 INFO    MainThread:31975 [wandb_init.py:init():460] starting backend
2023-03-11 08:44:08,379 INFO    MainThread:31975 [backend.py:_multiprocessing_setup():101] multiprocessing start_methods=fork,spawn,forkserver, using: spawn
2023-03-11 08:44:08,403 INFO    MainThread:31975 [backend.py:ensure_launched():216] starting backend process...
2023-03-11 08:44:08,410 INFO    MainThread:31975 [backend.py:ensure_launched():222] started backend process with pid: 2598
2023-03-11 08:44:08,412 INFO    MainThread:31975 [wandb_init.py:init():469] backend started and connected
2023-03-11 08:44:08,416 INFO    MainThread:31975 [wandb_init.py:init():533] updated telemetry
2023-03-11 08:44:08,442 INFO    MainThread:31975 [wandb_init.py:init():563] communicating current version
2023-03-11 08:44:09,293 INFO    MainThread:31975 [wandb_init.py:init():568] got version response upgrade_message: "wandb version 0.13.11 is available!  To upgrade, please run:\n $ pip install wandb --upgrade"

2023-03-11 08:44:09,295 INFO    MainThread:31975 [wandb_init.py:init():578] communicating run to backend with 30 second timeout
2023-03-11 08:44:39,298 INFO    MainThread:31975 [interface_shared.py:_communicate_run():313] couldn't get run from backend
2023-03-11 08:44:39,303 ERROR   MainThread:31975 [wandb_init.py:init():583] backend process timed out
2023-03-11 08:44:39,308 ERROR   MainThread:31975 [wandb_init.py:init():592] encountered error: Error communicating with wandb process
try: wandb.init(settings=wandb.Settings(start_method='fork'))
or:  wandb.init(settings=wandb.Settings(start_method='thread'))
For more info see: https://docs.wandb.ai/library/init#init-start-error
2023-03-11 08:44:39,328 ERROR   MainThread:31975 [wandb_init.py:init():958] error
Traceback (most recent call last):
  File "/opt/conda/lib/python3.7/site-packages/wandb/sdk/wandb_init.py", line 931, in init
    run = wi.init()
  File "/opt/conda/lib/python3.7/site-packages/wandb/sdk/wandb_init.py", line 596, in init
    backend.cleanup()
  File "/opt/conda/lib/python3.7/site-packages/wandb/sdk/backend/backend.py", line 245, in cleanup
    self.interface.join()
  File "/opt/conda/lib/python3.7/site-packages/wandb/sdk/interface/interface_shared.py", line 458, in join
    super().join()
  File "/opt/conda/lib/python3.7/site-packages/wandb/sdk/interface/interface.py", line 599, in join
    _ = self._communicate_shutdown()
  File "/opt/conda/lib/python3.7/site-packages/wandb/sdk/interface/interface_shared.py", line 455, in _communicate_shutdown
    _ = self._communicate(record)
  File "/opt/conda/lib/python3.7/site-packages/wandb/sdk/interface/interface_shared.py", line 213, in _communicate
    return self._communicate_async(rec, local=local).get(timeout=timeout)
  File "/opt/conda/lib/python3.7/site-packages/wandb/sdk/interface/interface_shared.py", line 218, in _communicate_async
    raise Exception("The wandb backend process has shutdown")
Exception: The wandb backend process has shutdown
2023-03-11 08:44:54,785 INFO    MainThread:31975 [wandb_settings.py:_apply_source_login():805] setting login settings: {}
2023-03-11 08:44:54,879 INFO    MainThread:31975 [wandb_setup.py:_flush():71] setting env: {}
2023-03-11 08:44:54,882 INFO    MainThread:31975 [wandb_setup.py:_flush():71] setting login settings: {}
2023-03-11 08:44:54,887 INFO    MainThread:31975 [wandb_init.py:_log_setup():371] Logging user logs to /workspace/nfl_utils/wandb/run-20230311_084454-371fl0m5/logs/debug.log
2023-03-11 08:44:54,891 INFO    MainThread:31975 [wandb_init.py:_log_setup():372] Logging internal logs to /workspace/nfl_utils/wandb/run-20230311_084454-371fl0m5/logs/debug-internal.log
2023-03-11 08:44:54,894 INFO    MainThread:31975 [wandb_init.py:init():404] calling init triggers
2023-03-11 08:44:54,897 INFO    MainThread:31975 [wandb_init.py:init():411] wandb.init called with sweep_config: {}
config: {}
2023-03-11 08:44:54,901 INFO    MainThread:31975 [wandb_init.py:init():460] starting backend
2023-03-11 08:44:54,904 INFO    MainThread:31975 [backend.py:_multiprocessing_setup():101] multiprocessing start_methods=fork,spawn,forkserver, using: spawn
2023-03-11 08:44:54,921 INFO    MainThread:31975 [backend.py:ensure_launched():216] starting backend process...
2023-03-11 08:44:54,929 INFO    MainThread:31975 [backend.py:ensure_launched():222] started backend process with pid: 3344
2023-03-11 08:44:54,932 INFO    MainThread:31975 [wandb_init.py:init():469] backend started and connected
2023-03-11 08:44:54,936 INFO    MainThread:31975 [wandb_init.py:init():533] updated telemetry
2023-03-11 08:44:55,007 INFO    MainThread:31975 [wandb_init.py:init():563] communicating current version
2023-03-11 08:44:55,730 INFO    MainThread:31975 [wandb_init.py:init():568] got version response upgrade_message: "wandb version 0.13.11 is available!  To upgrade, please run:\n $ pip install wandb --upgrade"

2023-03-11 08:44:55,732 INFO    MainThread:31975 [wandb_init.py:init():578] communicating run to backend with 30 second timeout
2023-03-11 08:44:56,314 INFO    MainThread:31975 [wandb_init.py:init():606] starting run threads in backend
2023-03-11 08:45:01,323 INFO    MainThread:31975 [wandb_run.py:_console_start():1810] atexit reg
2023-03-11 08:45:01,326 INFO    MainThread:31975 [wandb_run.py:_redirect():1684] redirect: SettingsConsole.REDIRECT
2023-03-11 08:45:01,327 INFO    MainThread:31975 [wandb_run.py:_redirect():1689] Redirecting console.
2023-03-11 08:45:01,329 INFO    MainThread:31975 [wandb_run.py:_redirect():1745] Redirects installed.
2023-03-11 08:45:01,330 INFO    MainThread:31975 [wandb_init.py:init():633] run started, returning control to user process
2023-03-11 08:45:10,456 INFO    MainThread:31975 [wandb_run.py:finish():1457] finishing run stgkrt/workspace-nfl_utils/371fl0m5
2023-03-11 08:45:10,459 INFO    MainThread:31975 [wandb_run.py:_atexit_cleanup():1780] got exitcode: 0
2023-03-11 08:45:10,461 INFO    MainThread:31975 [wandb_run.py:_restore():1752] restore
2023-03-11 08:45:18,073 INFO    MainThread:31975 [wandb_run.py:_wait_for_finish():1912] got exit ret: file_counts {
}
pusher_stats {
}

2023-03-11 08:45:18,431 INFO    MainThread:31975 [wandb_run.py:_wait_for_finish():1912] got exit ret: file_counts {
  wandb_count: 1
}
pusher_stats {
  total_bytes: 690
}

2023-03-11 08:45:18,534 INFO    MainThread:31975 [wandb_run.py:_wait_for_finish():1912] got exit ret: file_counts {
  wandb_count: 6
}
pusher_stats {
  uploaded_bytes: 690
  total_bytes: 43238
}

2023-03-11 08:45:18,644 INFO    MainThread:31975 [wandb_run.py:_wait_for_finish():1912] got exit ret: file_counts {
  wandb_count: 6
}
pusher_stats {
  uploaded_bytes: 690
  total_bytes: 43238
}

2023-03-11 08:45:18,782 INFO    MainThread:31975 [wandb_run.py:_wait_for_finish():1912] got exit ret: file_counts {
  wandb_count: 6
}
pusher_stats {
  uploaded_bytes: 690
  total_bytes: 43238
}

2023-03-11 08:45:18,897 INFO    MainThread:31975 [wandb_run.py:_wait_for_finish():1912] got exit ret: file_counts {
  wandb_count: 6
}
pusher_stats {
  uploaded_bytes: 690
  total_bytes: 43238
}

2023-03-11 08:45:19,015 INFO    MainThread:31975 [wandb_run.py:_wait_for_finish():1912] got exit ret: file_counts {
  wandb_count: 6
}
pusher_stats {
  uploaded_bytes: 43238
  total_bytes: 43238
}

2023-03-11 08:45:19,132 INFO    MainThread:31975 [wandb_run.py:_wait_for_finish():1912] got exit ret: file_counts {
  wandb_count: 6
}
pusher_stats {
  uploaded_bytes: 43238
  total_bytes: 43238
}

2023-03-11 08:45:19,249 INFO    MainThread:31975 [wandb_run.py:_wait_for_finish():1912] got exit ret: file_counts {
  wandb_count: 6
}
pusher_stats {
  uploaded_bytes: 43238
  total_bytes: 43238
}

2023-03-11 08:45:19,364 INFO    MainThread:31975 [wandb_run.py:_wait_for_finish():1912] got exit ret: file_counts {
  wandb_count: 6
}
pusher_stats {
  uploaded_bytes: 43238
  total_bytes: 43238
}

2023-03-11 08:45:19,477 INFO    MainThread:31975 [wandb_run.py:_wait_for_finish():1912] got exit ret: file_counts {
  wandb_count: 6
}
pusher_stats {
  uploaded_bytes: 43238
  total_bytes: 43238
}

2023-03-11 08:45:20,253 INFO    MainThread:31975 [wandb_run.py:_wait_for_finish():1912] got exit ret: file_counts {
  wandb_count: 6
}
pusher_stats {
  uploaded_bytes: 43238
  total_bytes: 43238
}

2023-03-11 08:45:20,973 INFO    MainThread:31975 [wandb_run.py:_wait_for_finish():1912] got exit ret: done: true
exit_result {
}
file_counts {
  wandb_count: 6
}
pusher_stats {
  uploaded_bytes: 43238
  total_bytes: 43238
}
local_info {
}

2023-03-11 08:45:22,294 INFO    MainThread:31975 [wandb_run.py:_append_files():2180] logging synced files
